config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :field_records
  resources :field_record_details
  match 'field_records/export_pgpi/:id' => 'field_records#export_pgpi', via: [:get, :post], defaults: {format: 'xml'}
  match 'field_records/export_data/:nendo/:rinpan/:shouhan' => 'field_records#export_data', via: [:get, :post], defaults: {format: 'html'}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field_record.rb
class FieldRecord < ApplicationRecord
  has_many :field_record_details, dependent: :destroy
  accepts_nested_attributes_for :field_record_details, allow_destroy: true
end

app/models/field_record_detail.rb
class FieldRecordDetail < ApplicationRecord
  belongs_to :field_record
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/field_record_details_controller.rb
class FieldRecordDetailsController < ApplicationController
  before_action :set_field_record_detail, only: [:show, :edit, :update, :destroy]
  before_action :prepare_common, :only => [:index]

  # GET /field_record_details
  # GET /field_record_details.json
  def index
    @field_record_details = FieldRecordDetail.all
  end

  # GET /field_record_details/1
  # GET /field_record_details/1.json
  def show
  end

  # GET /field_record_details/new
  def new
    @field_record_detail = FieldRecordDetail.new
  end

  # GET /field_record_details/1/edit
  def edit
  end

  # POST /field_record_details
  # POST /field_record_details.json
  def create
    @field_record_detail = FieldRecordDetail.new(field_record_detail_params)

    respond_to do |format|
      if @field_record_detail.save
        format.html { redirect_to @field_record_detail, notice: 'Field record detail was successfully created.' }
        format.json { render :show, status: :created, location: @field_record_detail }
      else
        format.html { render :new }
        format.json { render json: @field_record_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /field_record_details/1
  # PATCH/PUT /field_record_details/1.json
  def update
    respond_to do |format|
      if @field_record_detail.update(field_record_detail_params)
        format.html { redirect_to @field_record_detail, notice: 'Field record detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @field_record_detail }
      else
        format.html { render :edit }
        format.json { render json: @field_record_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /field_record_details/1
  # DELETE /field_record_details/1.json
  def destroy
    @field_record_detail.destroy
    respond_to do |format|
      format.html { redirect_to field_record_details_url, notice: 'Field record detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field_record_detail
      @field_record_detail = FieldRecordDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_record_detail_params
      params.fetch(:field_record_detail, {}).permit(:id, :bangou, :jushu, :tyokkei, :jukou, :hini, :budomari, :lat, :lon, :field_record_id)
    end

    def prepare_common
      # 樹種コード
      @tree_label = {
          1=>'イチイ',
          2=>'スギ',
          3=>'アカマツ',
          5=>'ヨーアカマツ',
          7=>'ゴヨウ',
          10=>'ストロブ',
          16=>'ヒバ',
          17=>'カラマツ',
          23 => 'トドマツ',
          25 => 'エゾマツ',
          26 => 'アカエゾ',
          27 => 'トウヒ',
          39 => 'ソノタ針',
          40 => 'コミ',
      }
    end
end

app/controllers/field_records_controller.rb
class FieldRecordsController < ApplicationController
  protect_from_forgery :except => [:create]
  before_action :set_field_record, only: [:show, :edit, :update, :destroy]
  before_action :prepare_common, :only => [:export_pgpi, :export_data]

  def export_pgpi
    @field_record_details = FieldRecordDetail.where(field_record_id: params[:id])
    # .gpx ファイルとして出力
    _filename = "立木調査野帳_#{params[:id].to_s}.gpx"
    headers['Content-Disposition'] = "attachment; filename=\'#{_filename}\'"
  end

  def export_data
    sql = <<-EOS
    SELECT kanriku, nendo, rinpan, bakku, shiban, shouhan, kubun, jushu, `tyokkei`, `jukou`, `hini`, `budomari`, COUNT(jushu) AS honsu
    FROM (SELECT * FROM `field_records` WHERE `nendo` = #{params[:nendo]} AND `rinpan` = #{params[:rinpan]} AND `shouhan` = #{params[:shouhan]}) fr
    INNER JOIN `field_record_details` frd ON frd.`field_record_id` = fr.`id`
    GROUP BY kanriku, nendo, rinpan, bakku, shiban, shouhan, kubun, jushu, `tyokkei`, `jukou`, `hini`, `budomari`
    ORDER BY jushu, `tyokkei`, `jukou`, `hini`, `budomari`;
    EOS

    @field_records = ActiveRecord::Base.connection.select_all(sql).to_hash
  end

  # GET /field_records
  # GET /field_records.json
  def index
    @field_records = FieldRecord.all
  end

  # GET /field_records/1
  # GET /field_records/1.json
  def show
  end

  # GET /field_records/new
  def new
    @field_record = FieldRecord.new
    @field_record.field_record_details.build
  end

  # GET /field_records/1/edit
  def edit
  end

  # POST /field_records
  # POST /field_records.json
  def create
    # @field_record = FieldRecord.new(field_record_params)
    @field_record = FieldRecord.create(field_record_params)

    respond_to do |format|
      if @field_record.save
        format.html { redirect_to @field_record, notice: 'レコードが追加されました' }
        format.json { render :show, status: :created, location: @field_record }
      else
        format.html { render :new }
        format.json { render json: @field_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /field_records/1
  # PATCH/PUT /field_records/1.json
  def update
    respond_to do |format|
      if @field_record.update(update_field_record_params)
        format.html { redirect_to @field_record, notice: '正常に更新されました' }
        format.json { render :show, status: :ok, location: @field_record }
      else
        format.html { render :edit }
        format.json { render json: @field_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /field_records/1
  # DELETE /field_records/1.json
  def destroy
    @field_record.destroy
    respond_to do |format|
      format.html { redirect_to field_records_url, notice: '正常に削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field_record
      @field_record = FieldRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_record_params
      params.fetch(:field_record, {}).permit(:id, :kanriku, :nendo, :rinpan, :bakku, :shiban, :shouhan, :kubun, :daihyou, field_record_details_attributes: [:bangou, :jushu, :tyokkei, :jukou, :hini, :budomari, :lat, :lon])
    end

    def update_field_record_params
      params.fetch(:field_record, {}).permit(:id, :kanriku, :nendo, :rinpan, :bakku, :shiban, :shouhan, :kubun, :daihyou, field_record_details_attributes: [:bangou, :jushu, :tyokkei, :jukou, :hini, :budomari, :lat, :lon, :_destroy, :id])
    end

    def prepare_common
      # 樹種コード
      @tree_label = {
          1=>'イチイ',
          2=>'スギ',
          3=>'アカマツ',
          5=>'ヨーアカマツ',
          7=>'ゴヨウ',
          10=>'ストロブ',
          16=>'ヒバ',
          17=>'カラマツ',
          23 => 'トドマツ',
          25 => 'エゾマツ',
          26 => 'アカエゾ',
          27 => 'トウヒ',
          39 => 'ソノタ針',
          40 => 'コミ',
      }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/field_record_details_helper.rb
module FieldRecordDetailsHelper
end

app/helpers/field_records_helper.rb
module FieldRecordsHelper
end

app/views/field_record_details/_form.html.slim
= form_for @field_record_detail do |f|
  table.table.table-bordered.table-hover.table-striped
    thead.thead-inverse
      tr.row
        th.col-md-1 野帳ID
        th.col-md-1 調査年度
        th.col-md-2 林班
        th.col-md-1 小班
        th.col-md-1 樹種
        th.col-md-1 直径
        th.col-md-1 樹高
        th.col-md-1 品位
        th.col-md-1 歩止
        th.col-md-1 緯度
        th.col-md-1 経度
    tbody
      tr.row
        td.col-md-1 = f.text_field :field_record_id, value: @field_record_detail.field_record_id
        td.col-md-1 = f.text_field :nendo, value: @field_record_detail.field_record.nil? ? '' : @field_record_detail.field_record.nendo
        td.col-md-1 = f.text_field :rinpan, value: @field_record_detail.field_record.nil? ? '' : @field_record_detail.field_record.rinpan
        td.col-md-1 = f.text_field :shouhan, value: @field_record_detail.field_record.nil? ? '' : @field_record_detail.field_record.shouhan
        td.col-md-1 = f.text_field :jushu, value: @field_record_detail.jushu
        td.col-md-1 = f.text_field :tyokkei, value: @field_record_detail.tyokkei
        td.col-md-1 = f.text_field :jukou, value: @field_record_detail.jukou
        td.col-md-1 = f.text_field :hini, value: @field_record_detail.hini
        td.col-md-1 = f.text_field :budomari, value: @field_record_detail.budomari
        td.col-md-1 = f.text_field :lat, value: @field_record_detail.lat
        td.col-md-1 = f.text_field :lon, value: @field_record_detail.lon

  .row
    - if @field_record_detail.errors.any?
      #error_explanation
        h2 = "#{pluralize(@field_record_detail.errors.count, "error")} prohibited this field_record_detail from being saved:"
        ul
          - @field_record_detail.errors.full_messages.each do |message|
            li = message

  .actions = f.submit '確定', class: "btn btn-primary"
  br

app/views/field_record_details/edit.html.slim
#field-record-edit
  .container-fluid
    .title.row
      span.col-md-12
        h4 立木データの編集

    == render 'form'

    = link_to 'キャンセル', field_record_details_path, :type=>"button", :class=>"btn btn-warning"

app/views/field_record_details/index.html.slim
h3 立木調査野帳
h4 立木データ
table.table.table-bordered.table-striped.table-hover
  thead.thead-inverse
    tr
      th 野帳ID
      th 樹種
      th 直径
      th 樹高
      th 品位
      th 歩止
      th 緯度
      th 経度
      th 作成日
      th 更新日
      th アクション
  tbody
    - @field_record_details.each do |field_record_detail|
      tr
        th scope="row"
          span = field_record_detail.field_record_id
        td
          span = @tree_label[field_record_detail.jushu]
          span = "[#{field_record_detail.jushu}]"
        td
          span = field_record_detail.tyokkei
        td
          span = field_record_detail.jukou
        td
          span = field_record_detail.hini
        td
          span = field_record_detail.budomari
        td
          span = field_record_detail.lat
        td
          span = field_record_detail.lon
        td
          span = field_record_detail.created_at.strftime('%Y年%m月%d日 %H:%M:%S')
        td
          span = field_record_detail.updated_at.strftime('%Y年%m月%d日 %H:%M:%S')
        td
          span
            = link_to(edit_field_record_detail_path(field_record_detail), {:type => "button", :class => "btn btn-default", :alt => "編集", :title => "編集"}) do
              span.glyphicon.glyphicon-pencil
          span
            = link_to(field_record_detail, {:type => "button", :class => "btn btn-default", :alt => "削除", :title => "削除", data: {confirm: '削除しますか?'}, method: :delete}) do
              span.glyphicon.glyphicon-remove style="color: red;"

br

= link_to '新規追加', new_field_record_detail_path, :type => "button", :class => "btn btn-primary"
= link_to '立木調査野帳へ戻る', field_records_path, :type => "button", :class => "btn btn-default"

app/views/field_record_details/new.html.slim
#field-record-new
  .container-fluid
    .title.row
      span.col-md-12
        h3 立木調査野帳
    .title.row
      span.col-md-12
        h4 新規追加(立木データ)

    == render 'form'

    = link_to 'キャンセル', field_record_details_path, :type => "button", :class => "btn btn-warning"

app/views/field_record_details/show.html.slim
p#notice = notice

= form_for @field_record_detail do |f|
  table
    thead
      tr
        th 調査番号
        th 樹種
        th 直径
        th 樹高
        th 品位
        th 歩止
        th 緯度
        th 経度
    tbody
      tr
        td = f.text_field :bangou, value: @field_record_detail.bangou
        td = f.text_field :jushu, value: @field_record_detail.jushu
        td = f.text_field :tyokkei, value: @field_record_detail.tyokkei
        td = f.text_field :jukou, value: @field_record_detail.jukou
        td = f.text_field :hini, value: @field_record_detail.hini
        td = f.text_field :budomari, value: @field_record_detail.budomari
        td = f.text_field :lat, value: @field_record_detail.lat
        td = f.text_field :lon, value: @field_record_detail.lon

= link_to '編集', edit_field_record_detail_path(@field_record_detail), :type => "button", :class => "btn btn-primary"
= link_to '戻る', field_record_details_path, :type => "button", :class => "btn btn-default"

app/views/field_records/_form.html.slim
= form_for @field_record do |f|
  table.table.table-bordered.table-hover.table-striped
    thead.thead-inverse
      tr.row
        th.col-md-1 野帳ID
        th.col-md-1 管理区
        th.col-md-2 調査年度
        th.col-md-2 林班
        th.col-md-2 伐区番号
        th.col-md-1 支番
        th.col-md-1 小班
        th.col-md-1 指定区分
        th.col-md-1 代表樹種
    tbody
      tr.row
        td.col-md-1 = f.text_field :id, value: @field_record.id
        td.col-md-1 = f.text_field :kanriku, value: @field_record.kanriku
        td.col-md-2 = f.text_field :nendo, value: @field_record.nendo
        td.col-md-2 = f.text_field :rinpan, value: @field_record.rinpan
        td.col-md-2 = f.text_field :bakku, value: @field_record.bakku
        td.col-md-1 = f.text_field :shiban, value: @field_record.shiban
        td.col-md-1 = f.text_field :shouhan, value: @field_record.shouhan
        td.col-md-1 = f.text_field :kubun, value: @field_record.kubun
        td.col-md-1 = f.text_field :daihyou, value: @field_record.daihyou

  table.table.table-bordered.table-hover.table-striped
    thead.thead-inverse
      tr.row
        th.col-md-2 樹種
        th.col-md-2 直径
        th.col-md-2 樹高
        th.col-md-1 品位
        th.col-md-1 歩止
        th.col-md-2 緯度
        th.col-md-2 経度
    = f.fields_for :field_record_details do |d|
      tbody
        tr.row
          td.col-md-2 = d.text_field :jushu
          td.col-md-2 = d.text_field :tyokkei
          td.col-md-2 = d.text_field :jukou
          td.col-md-1 = d.text_field :hini
          td.col-md-1 = d.text_field :budomari
          td.col-md-2 = d.text_field :lat
          td.col-md-2 = d.text_field :lon

  .row
    - if @field_record.errors.any?
      #error_explanation
        h2 = "#{pluralize(@field_record.errors.count, "error")} prohibited this field_record from being saved:"
        ul
          - @field_record.errors.full_messages.each do |message|
            li = message

  .actions = f.submit '確定', class: "btn btn-primary"
  br

app/views/field_records/edit.html.slim
#field-record-edit
  .container-fluid
    .title.row
      span.col-md-12
        h4 立木調査野帳の編集

    == render 'form'

    = link_to 'キャンセル', field_records_path, :type=>"button", :class=>"btn btn-warning"

app/views/field_records/export_data.html.slim
#export-data
  .container-fluid
    .title.row
      span.col-md-12
        h4 = '立木調査野帳'
  table.box-header.table.table-bordered.table-striped
    thead
      tr.row
        th.col-md-1 = '管理区'
        th.col-md-2 = '調査年度'
        th.col-md-2 = '林班'
        th.col-md-2 = '伐区番号'
        th.col-md-1 = '支番'
        th.col-md-2 = '小班'
        th.col-md-1 = '指定区分'
        th.col-md-1 = '代表樹種'
    tbody
      tr.row
        td.col-md-1 = @field_records[0]['kanriku']
        td.col-md-2 = @field_records[0]['nendo']
        td.col-md-2 = @field_records[0]['rinpan']
        td.col-md-2 = @field_records[0]['bakku']
        td.col-md-1 = @field_records[0]['shiban']
        td.col-md-2 = @field_records[0]['shouhan']
        td.col-md-1 = @field_records[0]['kubun']
        td.col-md-1 = @field_records[0]['jushu']
  table.box-main.table.table-bordered.table-striped
    thead
      tr.row
        th.col-md-1 = '調査番号'
        th.col-md-2 = '樹種'
        th.col-md-1 = '直径'
        th.col-md-1 = '樹高'
        th.col-md-1 = '品位'
        th.col-md-1 = '歩止(%)'
        th.col-md-1 = '本数'
        th.col-md-2 = '修正直径'
        th.col-md-2 = '備考'
    tbody
      - @field_records.each.with_index(1) do |field_record, bangou|
        tr.row
          td.col-md-1 = sprintf("%03d", bangou)
          td.main-jushu.col-md-2
            span = @tree_label[field_record['jushu']]
            span = "[#{field_record['jushu']}]"
          td.col-md-1 = field_record['tyokkei']
          td.col-md-1 = field_record['jukou']
          td.col-md-1 = field_record['hini']
          td.col-md-1 = field_record['budomari']
          td.col-md-1 = field_record['honsu']
          td.col-md-2 = ''
          td.col-md-2 = ''

app/views/field_records/index.html.slim
#field-record-index
  .container-fluid
    .title.row
      span.col-md-12
        h3 立木調査野帳
    .title.row
      span.col-md-12
        h4 野帳データ
    table.table.table-bordered.table-striped.table-hover
      thead.thead-inverse
        tr.row
          th
            |野帳ID
          th
            |管理区
          th
            |調査年度
          th
            |林班
          th
            |伐区
          th
            |支番
          th
            |小班
          th
            |区分
          th
            |代表樹種
          th
            |作成日
          th
            |最終更新日
          th
            |アクション
      tbody
        - @field_records.each do |field_record|
          tr.row
            th scope="row"
              span = field_record.id
            td
              span = field_record.kanriku
            td
              span = field_record.nendo
            td
              span = field_record.rinpan
            td
              span = field_record.bakku
            td
              span = field_record.shiban
            td
              span = field_record.shouhan
            td
              span = field_record.kubun
            td
              span = field_record.daihyou
            td
              span = field_record.created_at.strftime('%Y年%m月%d日 %H:%M:%S')
            td
              span = field_record.updated_at.strftime('%Y年%m月%d日 %H:%M:%S')
            td.action
              span
                - if !field_record.nendo.nil? && !field_record.rinpan.nil? && !field_record.shouhan.nil?
                  = link_to({:controller => :field_records, :action => :export_data, :nendo => field_record.nendo, :rinpan => field_record.rinpan, :shouhan => field_record.shouhan}, {:type=>"button", :class=>"btn btn-default", :alt=>"詳細", :title=>"詳細"}) do
                    span.glyphicon.glyphicon-list-alt
              span
                = link_to({:controller => :field_records, :action => :export_pgpi, :id => field_record.id}, {:type => "button", :class => "btn btn-default", :alt=>"pgpi出力", :title=>"pgpi出力"}) do
                  span.glyphicon.glyphicon-globe
              span
                = link_to(edit_field_record_path(field_record), {:type => "button", :class => "btn btn-default", :alt=>"編集", :title=>"編集"}) do
                  span.glyphicon.glyphicon-pencil
              span
                = link_to(field_record, {:type => "button", :class => "btn btn-default", :alt=>"削除", :title=>"削除", data: { confirm: "#{field_record.id} を削除しますか?" }, method: :delete}) do
                  span.glyphicon.glyphicon-remove style="color: red;"

    span = link_to '新規追加', new_field_record_path, :type => "button", :class => "btn btn-primary"
    span
      = link_to(field_record_details_path, {:type => "button", :class => "btn btn-default"}) do
        span.glyphicon.glyphicon-tree-conifer style="color: green;"
        |立木データ

app/views/field_records/new.html.slim
#field-record-new
  .container-fluid
    .title.row
      span.col-md-12
        h3 立木調査野帳
    .title.row
      span.col-md-12
        h4 新規追加

    == render 'form'

    = link_to 'キャンセル', field_records_path, :type => "button", :class => "btn btn-warning"

app/views/field_records/show.html.slim
p#notice = notice

= form_for @field_record do |f|
  table.table.table-bordered.table-hover.table-striped
    thead
      tr
        th ID
        th 管理区
        th 調査年度
        th 林班
        th 伐区
        th 支番
        th 小班
        th 区分
        th 代表樹種
    tbody
      tr
        td = f.text_field :id, value: @field_record.id
        td = f.text_field :kanriku, value: @field_record.kanriku
        td = f.text_field :nendo, value: @field_record.nendo
        td = f.text_field :rinpan, value: @field_record.rinpan
        td = f.text_field :bakku, value: @field_record.bakku
        td = f.text_field :shiban, value: @field_record.shiban
        td = f.text_field :shouhan, value: @field_record.shouhan
        td = f.text_field :kubun, value: @field_record.kubun
        td = f.text_field :daihyou, value: @field_record.daihyou

= link_to '編集', edit_field_record_path(@field_record), :type => "button", :class => "btn btn-primary"
= link_to '戻る', field_records_path, :type => "button", :class => "btn btn-default"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hph2017</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>